name: Deploy-to-EC2

# Trigger deployment only on push to master branch
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to EC2 on develop branch push
    runs-on: ubuntu-latest

    steps:
      - name: Checking out code
        uses: actions/checkout@v3
      - name: Installing Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "14"
      - name: Installing Dependencies
        run: npm install
      - name: Building Project
        run: npm run build
      - name: Deploy to AWS EC2
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          REMOTE_HOST: ${{ secrets.HOST_DNS }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          SOURCE: ${{ secrets.SOURCE_DIR }}
          TARGET: ${{ secrets.TARGET_DIR }}